# Generated by Django 4.1 on 2022-09-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramaccount',
            name='chat_id',
            field=models.CharField(max_length=100),
        ),
    ]
