# Generated by Django 4.1 on 2022-09-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchpage',
            name='terms_level_1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='searchpage',
            name='terms_level_2',
            field=models.TextField(null=True),
        ),
    ]
