# Generated by Django 4.0.1 on 2022-01-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_publisher_channel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='is_channel',
        ),
    ]
