# Generated by Django 4.0.1 on 2022-01-22 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_post_body'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('network', 'username')},
        ),
    ]
