# Generated by Django 4.0.1 on 2022-01-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0006_alter_channel_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="data",
            field=models.JSONField(null=True),
        ),
    ]
