# Generated by Django 4.0.1 on 2022-01-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_post_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
