# Generated by Django 4.0.1 on 2022-01-22 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_channel_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='network.network'),
        ),
    ]
