# Generated by Django 4.0.1 on 2022-01-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0009_alter_channel_network"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
