# Generated by Django 4.0.2 on 2022-02-19 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0014_keyword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyword",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keywords",
                related_query_name="keyword",
                to="network.post",
            ),
        ),
    ]
