# Generated by Django 4.0.2 on 2022-03-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0019_channel_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="ner",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="sentiment",
            field=models.JSONField(null=True),
        ),
    ]
