# Generated by Django 4.0.4 on 2022-05-13 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0024_channel_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="channel",
            old_name="type",
            new_name="language",
        ),
    ]
