# Generated by Django 4.0.4 on 2022-05-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0028_post_main_category_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("crawl_linkedin_feed", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
