# Generated by Django 4.0.5 on 2022-08-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0031_alter_channellistexport_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('keyword', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
