# Generated by Django 4.1.4 on 2022-12-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0036_outputchannel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutputChannel',
        ),
    ]
