# Generated by Django 4.0.4 on 2022-05-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("linkedin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpage",
            name="last_crawl_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
