# Generated by Django 4.1 on 2022-09-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0002_jobpage_last_crawl_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
