# Generated by Django 4.1.4 on 2022-12-18 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0036_outputchannel"),
        ("linkedin", "0003_jobpage_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpage",
            name="output_channel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linkedin_pages",
                to="network.outputchannel",
            ),
        ),
    ]
