# Generated by Django 4.1.4 on 2022-12-18 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("linkedin", "0004_jobpage_output_channel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobpage",
            name="output_channel",
        ),
    ]
