# Generated by Django 4.1.4 on 2022-12-18 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0003_channel"),
        ("linkedin", "0005_remove_jobpage_output_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpage",
            name="output_channel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linkedin_pages",
                to="notification.channel",
            ),
        ),
    ]
