# Generated by Django 4.1.4 on 2022-12-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("linkedin", "0006_jobpage_output_channel"),
    ]

    operations = [
        migrations.CreateModel(
            name="IgnoredContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("url", models.URLField(null=True)),
                ("content", models.TextField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
