# Generated by Django 4.1.4 on 2022-12-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("linkedin", "0007_ignoredcontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=20)),
                ("words", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="jobpage",
            name="keywords",
            field=models.ManyToManyField(to="linkedin.keyword"),
        ),
    ]
