# Generated by Django 4.1.4 on 2023-01-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("linkedin", "0010_ignoringfilter"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpage",
            name="ignore_filters",
            field=models.ManyToManyField(blank=True, to="linkedin.ignoringfilter"),
        ),
    ]
