# Generated by Django 4.1.4 on 2023-01-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0011_jobpage_ignore_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ignoringfilter',
            name='place',
            field=models.CharField(choices=[('location', 'location'), ('title', 'title'), ('company', 'company')], max_length=15),
        ),
    ]
