# Generated by Django 4.1.4 on 2023-01-07 03:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("linkedin", "0012_alter_ignoringfilter_place"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ignoredcontent",
            old_name="content",
            new_name="description",
        ),
    ]
