# Generated by Django 4.1.4 on 2023-01-07 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0013_rename_content_ignoredcontent_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IgnoredContent',
            new_name='IgnoredJob',
        ),
    ]
