# Generated by Django 4.1.4 on 2023-01-07 03:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0003_channel"),
        ("linkedin", "0014_rename_ignoredcontent_ignoredjob"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="JobPage",
            new_name="JobSearch",
        ),
    ]
