# Generated by Django 4.1.4 on 2023-01-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("linkedin", "0017_ignoredjob_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ignoredjob",
            name="company",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ignoredjob",
            name="location",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ignoredjob",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
