# Generated by Django 4.1.5 on 2023-01-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0023_jobsearch_page_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsearch',
            name='page_count',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='how many pages should be crawled'),
        ),
    ]
