# Generated by Django 4.1.5 on 2023-01-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("linkedin", "0025_jobsearch_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobsearch",
            name="priority",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                help_text="pages with higher priority, will be at the first of crawl queue",
            ),
        ),
    ]
