# Generated by Django 4.1.5 on 2023-02-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("linkedin", "0026_alter_jobsearch_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ignoredjob",
            name="language",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
