# Generated by Django 4.1.7 on 2023-04-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("linkedin", "0028_alter_ignoredjob_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("enable_job_crawls", models.BooleanField(default=False)),
                ("enable_feed_crawls", models.BooleanField(default=False)),
                ("enable_search_crawls", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
