# Generated by Django 4.1.7 on 2023-04-08 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("linkedin", "0029_config"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Config",
        ),
    ]
