# Generated by Django 4.2 on 2024-09-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0031_jobsearch_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ignoredjob',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
