# Generated by Django 4.2 on 2024-11-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0032_alter_ignoredjob_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsearch',
            name='just_easily_apply',
            field=models.BooleanField(default=False),
        ),
    ]
