# Generated by Django 4.2 on 2024-11-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0033_jobsearch_just_easily_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='ignoredjob',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
