# Generated by Django 4.2 on 2025-02-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0034_ignoredjob_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsearch',
            name='last_crawl_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='how many items was found', null=True),
        ),
    ]
