# Generated by Django 4.0.1 on 2022-01-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegram", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="phone_code_hash",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
