# Generated by Django 4.1 on 2022-09-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_account_phone_code_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
